utils::globalVariables(
    c(
        ".",
        "scAB_select",
        "gene_RNA_count_filter",
        "nFeature_RNA",
        "percent.mt",
        "Fraction",
        "Total",
        "..duplicate_cols"
    )
)
